services:
  node-app:
    image: node
    container_name: node-app
    working_dir: /app
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - '${PORT}:${PORT}'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_DIALECT=${DB_DIALECT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    image: node
    container_name: frontend-app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules # Importante: evita conflictos de binarios
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_PROXY_TARGET=http://node-app:3000 # Le indica al proxy a dónde apuntar
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    networks:
      - app-network
    command: bash -c "npm install && npm start -- --host"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
